"""create session_metrics table

Revision ID: d3330c50a587
Revises: abc110c8e93b
Create Date: 2026-08-08 19:40:08.334795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3330c50a587'
down_revision: Union[str, None] = 'abc110c8e93b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('wpm_overall', sa.Float(), nullable=False),
    sa.Column('wpm_rolling_windows', sa.JSON(), nullable=False),
    sa.Column('filler_count', sa.Integer(), nullable=False),
    sa.Column('filler_rate_per_100_words', sa.Float(), nullable=False),
    sa.Column('natural_pause_count', sa.Integer(), nullable=False),
    sa.Column('hesitation_pause_count', sa.Integer(), nullable=False),
    sa.Column('total_pause_duration_s', sa.Float(), nullable=False),
    sa.Column('longest_pause_s', sa.Float(), nullable=False),
    sa.Column('speech_to_silence_ratio', sa.Float(), nullable=False),
    sa.Column('mtld_score', sa.Float(), nullable=False),
    sa.Column('repeated_trigram_rate', sa.Float(), nullable=False),
    sa.Column('mean_length_utterance', sa.Float(), nullable=False),
    sa.Column('clauses_per_sentence', sa.Float(), nullable=False),
    sa.Column('subordination_ratio', sa.Float(), nullable=False),
    sa.Column('passive_voice_pct', sa.Float(), nullable=False),
    sa.Column('discourse_marker_rate_per_100_words', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_metrics_session_id'), 'session_metrics', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_metrics_session_id'), table_name='session_metrics')
    op.drop_table('session_metrics')
    # ### end Alembic commands ###
